### ISSUE TITLE
2019.12.24讨论及后续跟进

### ISSUE THREAD

**Issue by jexchan** [freeCodeCamp-China/ET-for-Kids#3]
时间：2019年12月24日
参与人：Miya / 书香 / 嫂子 / 阿秋 / 显军

## 关于项目

暂时不用以前的 Geeks and Kids，改用 ET for Kids，E 代表 Engineer，T 代表 Teacher

### 关于 Slogan 的一些 ideas
- 连接（connection） ，连接 ET 和 Kids ，连接Kids 和 Kids，连接小环境与大世界
- 为孩子打开一扇窗，看到一个更大的世界
  - Programming for Kids, to see a big world ？

### 所含项目或产品

ET for Kids 是总的项目名，有点像 TEDx在下面可以有各种相关的项目、活动、产品等
- 给身边的孩子上一堂编程启蒙课 （持续的主题活动）
- 连接志愿者，为学校学生带来公益编程课（讨论到龙泉的一些学校）
- 与 FCC 联合的线下工作坊
- 有一定影响力后，将连接到的人集中到一起，开一个大聚会

### 关于风险

由于考虑到项目本身与孩子直接相关，存在一定风险（比如说孩子的安全、性侵等），经大家讨论，有一些相关措施
- 活动相关课程、流程等全放在 Github ，以 issue 形式出现，不以 FCC 或个人的名义去发
- 不搞线下老师培训
- 今年春节的活动最低情况下由我们小圈子信任的人去做
- 咨询一下律师，操作相关的活动存在哪些风险，怎么做可以规避

### 启动原则

尽可能以最小行动、最低风险原则来执行，降低对大家的工作量的同时，保证工作持续进行下去

## TODOs
- 准备编程启蒙课  by @可好玩乐
   - [ ] 课程 PPT
   - [ ] Teacher Notes，引导老师如果去上课的一些关键点
   - [ ] 编程任务，用与课堂与课后练习
-  [ ] 准备给身边孩子带一堂编程启蒙课的相关执行流程
- 与活动相关的准备工作
   - [ ] 域名？
   - [ ] 需要一定的开发工作？如活动页面、信息提前等
- [ ] 咨询一下律师，操作相关的活动存在哪些风险，怎么做可以规避  @jexchan @Miya
- [ ] 录制一点介绍宣传视频 @阿秋 @书香
